# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5071781129f7ea7be8ab1aa6cf8e12b5d0fe7f8f390c2771c98c016bff696bea780261c695ffcb3fcd03b129538d3692b0b42075a92d7e48168b9f70dbb9de33

test:
  secret_key_base: 343d6b649b8f02aa33b4f3e464160183ab9df6152c69687732e260b19cf3a068157f11a6147c401b0e94c5998b7341b9d215afea35e47ad4bec0eaf59f01a88c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
